spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/task_agile
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9090

logging:
  level:
    com.taskagile: DEBUG
    org.springframework.security: DEBUG